#!/bin/sh

SYNC_USER=${SYNC_USER:-gitsync}
SYNC_UID=${SYNC_UID:-1000}
SYNC_GROUP=${SYNC_GROUP:-gitsync}
SYNC_GID=${SYNC_GID:-1000}
SYNC_HOME=${SYNC_HOME:-/home/$SYNC_USER}

GIT_PACK_WINDOW_MEMORY=${GIT_PACK_WINDOW_MEMORY:-1g}
GIT_PACK_SIZE_LIMIT=${GIT_PACK_SIZE_LIMIT:-1g}

set -e

if ! id $SYNC_USER > /dev/null 2>&1; then
    if id $SYNC_UID > /dev/null 2>&1; then
        deluser $SYNC_UID
    fi

    addgroup --system \
             --gid $SYNC_GID \
             $SYNC_GROUP

    adduser --system \
            --home "$SYNC_HOME" \
            --uid $SYNC_UID \
            --gid $SYNC_GID \
            --shell /bin/sh \
            --disabled-password \
            $SYNC_USER

    if [ -e "$SYNC_HOME/.ssh" ]; then
        chown -R $SYNC_UID:$SYNC_GID $SYNC_HOME/.ssh
    fi
fi

# Configure git
su -c "git config --global pack.windowMemory ${GIT_PACK_WINDOW_MEMORY}"
su -c "git config --global pack.packSizeLimit ${GIT_PACK_SIZE_LIMIT}"

cd /usr/src/app
su -c "bundle exec ./git-sync $*" $SYNC_USER

